sonar.projectKey=guardian-test
sonar.projectName=guardian-test
sonar.organization=alpinesg
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,dist/**,coverage/**

# Quality gate thresholds
sonar.qualitygate.wait=true
